import type { Metadata } from "next";
import "@/app/ui/globals.css";
import Navbar from "@/app/_components/Navbar";
import { inter } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased max-w-4xl mx-auto`}
        cz-shortcut-listen="true"
      >
        <section>
          <Navbar />

        </section>
        {children}
      </body>
    </html>
  );
}
